import React, { Fragment } from 'react'
import './style.css'

export default function Modal() {
    return (
        <Fragment>
            <div className='modal-mask' />
            <div className='modal-message'>
                I'm a modal message
            </div>
            <div>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Suspendisse venenatis ultricies nunc, nec euismod mi vestibulum a. Ut dapibus sem vitae dolor convallis, ac feugiat leo egestas. Maecenas pretium scelerisque congue. Sed egestas ac eros vitae sagittis. Integer vestibulum dolor ac risus rutrum bibendum. Pellentesque erat nibh, dictum eget risus vitae, posuere accumsan lorem. Praesent sagittis malesuada pretium. Vivamus sed lectus sit amet nulla mollis bibendum. Nulla nec libero lorem. Suspendisse potenti. Suspendisse hendrerit nibh nec lectus feugiat placerat. Nam dapibus ultricies tempus. Aliquam sed luctus ligula. Cras luctus est mi. Suspendisse potenti.

Mauris commodo, mi non sodales condimentum, turpis odio ultrices velit, vitae consequat justo lectus in est. Ut at laoreet arcu, eget tristique est. Integer efficitur placerat ligula id porttitor. Aenean augue nibh, laoreet vitae metus ut, tincidunt consequat ipsum. Nam in dolor ornare, volutpat metus sit amet, lobortis leo. Cras ac accumsan quam, quis tempor ex. In eleifend metus quis lorem finibus porta. Vivamus libero orci, dignissim quis elementum non, maximus a velit. Sed lobortis, nisl eu efficitur tempus, ante lectus sollicitudin urna, et rutrum orci ligula in felis. Nunc a dui non mi maximus congue. Vestibulum purus libero, rhoncus sit amet nunc ut, congue imperdiet mi. Aenean molestie mauris ut nunc venenatis ullamcorper. Cras dignissim, eros in egestas molestie, tellus diam efficitur velit, ac fermentum nibh metus ac orci.

Fusce vehicula eleifend cursus. Integer ut aliquet dolor. Quisque sed varius eros. Aliquam porta imperdiet porttitor. Aliquam felis tellus, ullamcorper sit amet arcu eget, luctus placerat nibh. Maecenas ac magna tempus ipsum blandit tempus. Etiam velit dolor, condimentum sed massa non, porttitor dapibus arcu. Duis sollicitudin augue eu scelerisque sagittis. In velit lectus, scelerisque in luctus nec, aliquet volutpat dui. Duis pretium laoreet libero sit amet vulputate. Donec est massa, elementum quis maximus et, volutpat eget eros.

Cras lobortis turpis sed purus finibus suscipit. Quisque ac luctus enim, sit amet tempor mauris. Praesent pretium ullamcorper egestas. Ut tincidunt, mauris ac feugiat lobortis, velit metus facilisis sapien, at dictum enim odio non nunc. Nullam nibh lorem, accumsan eget porta quis, finibus in tortor. Vivamus id libero ornare, pulvinar lectus a, facilisis odio. Donec eu lobortis velit, at sollicitudin leo.

Proin sed placerat diam. Nam pharetra odio id tellus faucibus, nec congue metus pellentesque. Aenean efficitur at mauris at porta. Donec ac elit in ante aliquet dapibus non vitae diam. Pellentesque dignissim ultrices justo ut mattis. Nullam lacinia nibh a arcu suscipit vehicula. Suspendisse a leo vel mauris convallis consectetur quis a augue. Fusce tempus velit tellus, vulputate rhoncus ligula aliquam eu. Quisque sodales faucibus ornare. In laoreet, ante ac dictum consectetur, dolor est finibus orci, eget commodo erat tellus et mi. Nullam mollis tristique justo, non hendrerit enim posuere vitae. Donec diam diam, efficitur vel varius quis, mattis eget felis.

Maecenas varius tellus et mollis condimentum. Integer libero velit, rutrum a mi vel, interdum hendrerit neque. Mauris cursus velit vel nisl tincidunt finibus. Curabitur ut imperdiet nisl, quis porttitor diam. Aenean tristique ornare risus ut efficitur. Nulla consequat porttitor enim in vehicula. Curabitur nec euismod ipsum.

Aenean pretium risus quis volutpat mollis. Aliquam erat volutpat. Donec sagittis mauris id est consequat consequat. Cras dui metus, porta sed ultrices ac, scelerisque vel dui. Curabitur imperdiet malesuada dolor, et aliquam dolor suscipit nec. Quisque non est commodo, rhoncus lacus et, rhoncus ipsum. Etiam leo velit, consequat hendrerit auctor in, porta ac nibh. Curabitur eget sapien malesuada, bibendum ex nec, pretium justo. Pellentesque auctor ipsum sem, sed bibendum quam egestas quis. Cras finibus quis urna vulputate eleifend. Proin tempor diam porttitor sem viverra lobortis. Sed pulvinar tempus libero, vel commodo orci finibus malesuada. Praesent convallis sagittis pretium. Sed ut diam purus. Aenean auctor nisl ut porttitor suscipit. Aenean pretium turpis ipsum, ac maximus mi accumsan et.

Sed ullamcorper interdum orci quis cursus. Aenean dignissim iaculis justo at finibus. Vivamus ac tortor in nisi congue consectetur vitae eget justo. Integer vitae tortor ac nunc mollis convallis a vel lectus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec maximus posuere tortor, id fermentum tortor pretium at. Aliquam erat volutpat. Morbi a eros neque.

Nulla facilisi. Suspendisse in consequat metus. Sed rutrum enim sit amet massa consectetur, a ornare metus laoreet. Aliquam facilisis quam ut finibus accumsan. Curabitur interdum viverra aliquet. Proin dictum mollis sem, ac euismod nulla. Vestibulum blandit pretium dignissim. Vestibulum egestas porta elit, at vulputate lectus consectetur non. Curabitur sodales mi at erat sodales sagittis. Cras vestibulum lorem non magna facilisis egestas. In a augue magna. Aliquam eu mauris nisl. Suspendisse potenti.

Duis diam erat, feugiat ut turpis vel, tincidunt dapibus lorem. Nullam vulputate magna vel pellentesque aliquam. Quisque quis ipsum faucibus, consequat tellus a, pellentesque nisi. Nullam nec purus et dui euismod placerat quis et eros. Sed a lacus dictum, vestibulum tortor ac, efficitur magna. Vivamus elementum nulla odio, id vestibulum lorem cursus et. Fusce congue velit arcu, eu fringilla ipsum efficitur varius. Donec libero massa, semper a purus a, ullamcorper sollicitudin ipsum. Fusce nec vestibulum diam, nec ornare eros. Integer ultrices eleifend tincidunt.

Vivamus bibendum ex eu magna lobortis, non scelerisque odio eleifend. Nullam tempus, augue eu malesuada convallis, odio diam viverra eros, eget ultrices mi dui blandit diam. Aliquam et diam ut nibh feugiat volutpat sit amet eu est. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus dignissim velit in auctor commodo. Cras porta lectus ut pharetra imperdiet. Nunc faucibus malesuada urna at posuere. Vivamus vitae augue in felis pharetra aliquet id auctor ante. Interdum et malesuada fames ac ante ipsum primis in faucibus. Etiam bibendum ante quam, nec commodo mi vestibulum vitae. Aliquam in iaculis dolor. Maecenas molestie malesuada quam. Vestibulum varius nisl in tempor pretium. Nullam ultricies, nunc in volutpat consectetur, justo est porta nisi, sed ultrices risus mauris ut leo. Vestibulum interdum ornare nisl ac hendrerit. Suspendisse potenti.

Maecenas vel enim interdum, ultricies purus quis, lobortis ligula. Suspendisse dapibus, arcu in luctus varius, massa nulla porta quam, non faucibus dui diam non dui. Pellentesque nec faucibus odio. Cras dapibus porta ligula, pellentesque auctor tellus placerat vitae. Curabitur commodo vehicula nulla, et consectetur elit congue at. Vestibulum tincidunt nunc velit, et fermentum nisi lacinia at. Suspendisse potenti. Etiam et feugiat nibh, eget placerat sapien. Phasellus nec urna vel nulla tristique accumsan et in diam. Duis faucibus pretium accumsan. Pellentesque imperdiet nisi nec nulla sollicitudin lobortis. Duis blandit tortor sit amet sodales finibus.

Cras nec scelerisque ex. Aenean facilisis odio ut nulla efficitur, non suscipit diam fringilla. Nulla quis enim pharetra, tincidunt risus et, condimentum lectus. Curabitur quis dolor tincidunt, gravida quam et, lacinia magna. Pellentesque at maximus ante. Phasellus placerat, tellus eu rhoncus bibendum, dolor ex porttitor ante, a semper eros mi quis nisl. Integer sagittis vestibulum nunc, sed fermentum lacus ultrices vel. Nulla posuere leo ac accumsan pretium. Integer commodo sed libero sed condimentum. Etiam ultrices nibh lorem, sit amet interdum mauris lobortis vel. Pellentesque scelerisque augue sit amet magna placerat pellentesque.

Nulla facilisi. Sed quis lorem a libero accumsan viverra sed vel libero. Nulla eu laoreet ante. Phasellus malesuada, dui vel egestas porttitor, lacus justo feugiat dui, ut condimentum neque tellus ac ex. Integer maximus mi id elit pulvinar porta. Donec malesuada fermentum lorem a imperdiet. Aenean iaculis ante eros, sit amet imperdiet velit scelerisque auctor. Curabitur rhoncus ut metus id hendrerit. Maecenas aliquam urna non euismod varius. Nunc semper mattis metus ut ornare. Phasellus vel faucibus diam. Aenean molestie pulvinar tortor, non consectetur ante pretium ut. Donec hendrerit mattis fermentum. Mauris placerat efficitur enim nec egestas. Maecenas feugiat enim odio, vel aliquet tortor dictum sit amet.

Nulla facilisi. Integer fringilla diam ac blandit finibus. Cras condimentum cursus augue, eu rutrum orci consectetur vitae. Integer bibendum ligula arcu, eu pellentesque odio eleifend id. Duis vel tellus accumsan, aliquet urna in, tincidunt purus. Maecenas sapien ipsum, finibus non augue vel, efficitur sodales felis. In rhoncus interdum metus, vel eleifend lectus aliquam quis. Pellentesque eu nisi sit amet velit interdum dapibus. Vivamus sed tortor sem. Nulla vel interdum mi, nec pellentesque dolor. Mauris mollis tellus turpis. Nunc feugiat, neque ut suscipit auctor, lectus lectus rhoncus augue, ac sollicitudin leo ex ac est.

Cras euismod, lorem ac efficitur faucibus, turpis mi pretium sapien, vitae consequat quam dolor sit amet sem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Praesent cursus, eros quis pretium hendrerit, sapien lacus sollicitudin dui, eu volutpat arcu orci eu eros. Vivamus cursus neque non massa tincidunt imperdiet. Donec arcu odio, vulputate ut nulla ut, pulvinar elementum lacus. Nam sagittis bibendum purus eget lacinia. Duis in justo eu diam blandit consequat id et ipsum. Suspendisse nec elit vel nibh sollicitudin dapibus ac quis quam. Nam volutpat, orci sed consectetur placerat, erat nisi placerat sapien, vel hendrerit mi metus sed risus. Morbi vitae quam ut odio efficitur posuere vel in nibh. Integer enim neque, pharetra vel mauris ut, congue tempor nulla. Vivamus accumsan risus quis egestas varius. Etiam dignissim, erat et ultricies laoreet, sem nisi hendrerit purus, in rhoncus lectus mi eget ante. Nulla pulvinar tellus est, in ullamcorper nibh porta ac.

In congue ante risus. Vestibulum ut ante ac lorem dignissim porta a a felis. Morbi vestibulum eget nisi semper porttitor. Nam non nunc vitae lectus commodo semper a in erat. Maecenas accumsan sollicitudin elit. Nullam lobortis lacus ut velit consectetur porttitor. Nulla auctor tortor purus, quis eleifend elit viverra vitae. Nullam hendrerit placerat velit, ut vestibulum magna varius sagittis. Mauris semper mauris eget augue maximus, vel consectetur nisi ultrices. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In suscipit sed nisi quis fringilla. Cras accumsan pulvinar consequat. Nam laoreet est quis dolor sollicitudin tempus non ac augue. Phasellus at libero et metus tristique vulputate. Phasellus imperdiet felis mi, condimentum aliquet arcu tincidunt id.

Nullam porta nunc eu neque faucibus, vitae volutpat ex congue. Vivamus viverra efficitur nisi, suscipit pharetra urna accumsan ut. Quisque luctus, diam ac rhoncus ullamcorper, mauris nulla interdum est, ut tristique lacus est viverra arcu. Donec bibendum fringilla dolor, convallis ullamcorper urna. Aenean semper pharetra urna, nec luctus tortor suscipit non. Nunc feugiat tellus consequat leo tincidunt euismod. Sed fringilla arcu magna, in aliquet risus interdum id. Etiam ex mi, tincidunt ac interdum a, congue vitae enim. Etiam bibendum molestie nunc, sed aliquam enim facilisis eget. Curabitur turpis arcu, tincidunt vel tortor nec, sollicitudin laoreet enim. Vivamus sodales scelerisque turpis ut bibendum. Aliquam vel massa ac quam semper consequat eu vel nulla. Praesent ac ante dolor. Pellentesque lectus nunc, euismod eu convallis at, dignissim et sem.

Nam varius fermentum tortor eget vestibulum. Aliquam erat volutpat. Morbi nisl felis, iaculis at massa eget, malesuada facilisis lectus. Ut egestas, sapien nec pharetra scelerisque, velit sapien euismod enim, nec congue leo nisi pulvinar felis. Curabitur vehicula ex mauris, a posuere diam mollis non. Pellentesque imperdiet ipsum massa. Vivamus vitae mattis nisi. Nulla hendrerit congue ipsum, ut dictum urna commodo ut. Cras maximus sit amet mauris ac dictum. Fusce luctus dignissim augue id accumsan. Nam ullamcorper pellentesque lacus, id porta sapien interdum at. Donec feugiat, erat sit amet accumsan fringilla, sem magna faucibus nulla, quis placerat urna enim vitae purus.

Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce eget ultrices dui, id mollis nibh. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque eu purus eget libero pharetra consectetur. Vivamus tempus porta eros, eu dictum enim condimentum et. Nulla quam mi, vestibulum sit amet laoreet quis, posuere dignissim ante. Nullam rhoncus ultrices mi ac facilisis.


            </div>
        </Fragment>
    )
}